"use client";
import '@/assets/css/app.scss'
import Image from 'next/image';
import Illustration from '@/assets/img/illustration.png';
import { useAppDispatch, useAppSelector } from '@/redux/hooks/hooks';
import { RootState } from '@/redux/store/store';
import { useRouter } from 'next/navigation';
import { logOutUser } from '@/redux/store/slices/AuthSlice';
import { useEffect } from 'react';
import { userEvent } from '@/redux/store/slices/EventSlice';
import { usePathname } from 'next/navigation';
import Loader from '@/components/forms/Loader';
const languages = [{ id: 1, name: "English" }, { id: 2, name: "Danish" }];

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children, params}: { children: React.ReactNode, params: { event_id: string } }) {
    const dispatch = useAppDispatch();
    const pathname = usePathname();
    console.log(pathname)
    const {loading, event, event_orders} = useAppSelector((state: RootState) => state.event);

    useEffect(() => {
      const promise = dispatch(userEvent({event_id:params.event_id}));  
    
      return () => {
        promise.abort();
      }
    }, []);
    
  return (
    <>
    {(loading === false && event !== null) ?
        <>
            <div className="top-landing-page">
                    <div className="row d-flex">
                    <div className="col-8">
                        <div className="logo">
                        <a href="">
                            <Image
                            src={event?.brand_logo !== '' ? `${process.env.serverImageHost}/assets/event/branding/${event?.brand_logo}`: require("@/assets/img/logo.svg")}
                            alt=""
                            width="200"
                            height="29"
                            className="logos"
                            />
                        </a>
                        <div className="ebs-bottom-header-left">
                            <h3>
                            <a href="#!">{event?.event_name}</a>
                            </h3>
                            <ul>
                            <li>
                                <i className="material-symbols-outlined">calendar_month</i>{event?.event_date}
                            </li>
                            <li>
                                <i className="material-symbols-outlined">place</i>{event?.event_location}
                            </li>
                            </ul>
                        </div>
                        </div>
                    </div>
                    <div className="col-4">
                        <div className="right-top-header">
                        {!pathname.includes('invoice') && (event?.payment_settings?.eventsite_billing === 1) ? <button className="btn btn-default">
                            <i className="material-symbols-outlined">add</i> Create Order
                        </button> : null}
                        {pathname.includes('invoice') ? 
                            <>
                            <button className="btn btn-default">
                                <i className="material-symbols-outlined">sim_card_download</i> PDF
                            </button>
                            <button className="btn btn-default btn-send-order">
                                <i className="material-symbols-outlined">send</i> Send Order
                            </button> 
                            </>
                        : null}
                        </div>
                    </div>
                    </div>
                </div>
            <div style={{ background: "#fff" }} className="main-data-table">
                    {children}
            </div>
        </> :null}
      {loading === true && <Loader className=''fixed='' />}
      {loading === false && event === null ? 
      <div>
        No event found..
      </div> : null }
    </>
  )
}
